### ISSUE TITLE
GHA failing for mac (armadillo)

### ISSUE THREAD

**Issue by josephwb** [FePhyFoFum/phyx#185]
Getting a build fail for mac when it hits armadillo:
```
cont_models.cpp:4:10: fatal error: 'armadillo' file not found
```
The relevant GHA lines are:
```
    steps:
    - uses: actions/checkout@v4
    - name: Install brew dependencies
      if: runner.os == 'macOS'
      run:
          brew install nlopt armadillo automake autoconf
```
So, brew is failing to install armadillo? Will try to find a mac to troubleshoot this on...
